server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://examadmin:vasanth1208@cluster0.3l6idwb.mongodb.net/online_exam_db?retryWrites=true&w=majority&appName=Cluster0

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: online.exam.system10@gmail.com
    password: ehcmrshcxlsikvwp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

logging:
   level:
    org.springframework.web: DEBUG